services:
  # This is the postgres DB, which takes care of previous searches and authentication
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentimentanalyzer
    ports:
      - "5432:5432"

  # This is the neo4j DB, which is used for the sentiment links
  neo4j_db:
    image: neo4j:latest
    volumes:
      - ./data_pipeline/neo4j_data/:/data
    environment: 
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
